# Train options
train_opt:
    # training hyperparameters
    loss_type_enc_dec: 'mse'
    loss_type_cyc: 'mse'
    loss_type_id: 'pearson'
    loss_type_disc: 'hinge'
    loss_type_mmd: 'mmd'
    loss_type_coral: 'coral'
    lambda_cyc: 5
    lambda_id: 4
    lambda_adv: 1
    lambda_disc: 1
    lambda_mmd: 0.3
    lambda_coral: 0.3
    lambda_gp: 3
    interval_enc_dec: 1
    interval_id: 1
    interval_cyc: 1
    interval_adv: 1
    interval_disc: 1
    interval_mmd: 1
    interval_coral: 1
    batch_size: 128
    epochs_enc_dec: 100
    fix_weight_enc_dec: true
    epochs: 50
    # split-related data config
    cv_gene: 5
    cv_sample: 5
    target_fold_gene: null
    target_fold_sample: null
    # others
    device: 'cuda:7'
    num_workers: 4
    log_dir: '/home/abudhkar/gene_impute_code/logs/'
    
# Data options
data_opt:
    # Dataset domains
    domain_source: nanostring
    domain_target: gse
    # dataframe options
    gene_selection_count_source: null
    clip_outlier_source: true
    min_count_gene_source: 0
    min_count_cell_source: 0
    min_density_gene_source: 0.05
    min_density_cell_source: 0.1
    normalization_source: 'sqrt'
    min_count_gene_target: 0
    min_count_cell_target: 0
    gene_selection_count_target: 1000
    gene_selection_count_target: 2000
    clip_outlier_target: true
    min_density_gene_target: 0.05
    min_density_cell_target: 0.1
    normalization_target: 'sqrt'
    # image options (only applicable for NanoString)
    normalization_img: 'minmax1'
    exclude_background: true
    background_value: -1
    input_size_image: [224,224]
# Model options
model_opt:
    # model architecture for encoder
    enc_type_source: '1d_simple'
    enc_type_target: '1d_simple'
    # parameters for 1D model
    enc_features_source: [2048, 1024, 512]
    dec_features_source: [512, 1024, 2048]
    disc_features_source: [256, 128, 128, 64]
    latent_dim_source: 512
    enc_features_target: [2048, 1024, 512]
    dec_features_target: [512, 1024, 2048]
    disc_features_target: [256, 128, 128, 64]
    latent_dim_target: 2048 #512
    trans_features_s2t: [512, 512, 512, 1024, 1024] #[512, 256, 256, 128, 128]
    trans_features_t2s: [512, 256, 256, 128, 128]
    # parameters for image model (if given)
    img_model_arch: 'densenet121'
    in_channels_image: 5
    enc_type_img_1d: '1d_simple'
    enc_features_img: [4096, 1024, 512]
    latent_dim_img: 512
    img_model_pretrained: true
    # merge parameters (if given)
    merge_features: [512, 512, 512]
    latent_dim_merge: 512
